Update required Java version in README
Building with Java 14 results in the following error:

```
./sparrow/src/main/java/com/sparrowwallet/sparrow/whirlpool/dataSource/SparrowWalletStateSupplier.java:64: error: pattern matching in instanceof is a preview feature and is disabled by default.
            if(externalDestination.getPostmixHandler() instanceof SparrowPostmixHandler sparrowPostmixHandler) {
```